### PR TITLE
Added phpstan's source repository

### PR DESCRIPTION
**Pull request by derrabus**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks. Did you consider adding an extra.thanks entry in the composer.json of phpstan/phpstan?
See e.g. https://github.com/symfony/webpack-encore-bundle/blob/master/composer.json#L37

**Comment by derrabus** [comment]
I did not. Is that the preferred way to link the repositories? In that case, I will open a PR there.

**Comment by nicolas-grekas** [comment]
Yes, that's preferred: each package takes responsibility, only meta-repo are listed here.
At least this should be discussed there first.

**Comment by derrabus** [comment]
phpstan/phpstan#3554

**Comment by derrabus** [comment]
I've received _very_ quick feedback on this. 🤔 I think, we can close this PR then.

**Pull request closed without merging**
